src/main/java/uk/ac/cam/cl/dtg/segue/etl/ETLManager.java

I missed this part in the [ScheduledExecutorService docs](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledExecutorService.html#scheduleAtFixedRate-java.lang.Runnable-long-long-java.util.concurrent.TimeUnit-): ` If any execution of the task encounters an exception, subsequent executions are suppressed.`. 
Also adding the ability to configure the task period.

Make ETL task recoverable and configurable

---

web-api-live.xml
web-api-local.xml

Ticket: https://github.com/isaaccomputerscience/isaac-cs-issues/issues/20

[20]: Disable directory viewing as xml context parameter

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacade.java

[Ticket](https://github.com/isaaccomputerscience/isaac-cs-issues/issues/161)
Implement the numberAttended count expected by the front-end

[161]: Implement numberAttended count in getEventOverviews

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/managers/EventNotificationEmailManager.java

[Ticket](https://github.com/isaaccomputerscience/isaac-cs-issues/issues/159)
Modified sendReminderEmails method to send an alternate template if the event is scheduled for the day the job is run.

[159]: Implement email scheduling for event_reminder_same_day

---

pom.xml

This should fix https://github.com/isaaccomputerscience/isaac-api/security/dependabot/1.

Fix Bouncy Castle For Java LDAP injection vulnerability

---

src/main/java/uk/ac/cam/cl/dtg/segue/database/GitDb.java
src/main/java/uk/ac/cam/cl/dtg/segue/database/PostgresSqlDb.java

These include deprecated methods, missing documentation and incorrect usage of stack trace.

Fix multiple small issues with PostgresSqlDb and GitDB

---

src/main/java/uk/ac/cam/cl/dtg/isaac/dos/PgUserStreakManager.java
src/main/java/uk/ac/cam/cl/dtg/segue/api/AdminFacade.java
src/main/java/uk/ac/cam/cl/dtg/segue/api/InfoFacade.java
src/main/java/uk/ac/cam/cl/dtg/segue/api/managers/UserBadgeManager.java
src/main/java/uk/ac/cam/cl/dtg/segue/api/useralerts/UserAlertsWebSocket.java
src/main/java/uk/ac/cam/cl/dtg/segue/comm/AbstractCommunicationQueue.java
src/main/java/uk/ac/cam/cl/dtg/segue/configuration/SegueGuiceConfigurationModule.java
src/main/java/uk/ac/cam/cl/dtg/segue/etl/ETLConfigurationModule.java
src/main/java/uk/ac/cam/cl/dtg/segue/etl/ETLManager.java

This also includes other minor fixes and optimisations.

Remove usages of printStackTrace

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacade.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dao/EventBookingPersistenceManager.java
src/main/java/uk/ac/cam/cl/dtg/segue/scheduler/jobs/DeleteEventAdditionalBookingInformationJob.java
src/main/java/uk/ac/cam/cl/dtg/segue/scheduler/jobs/DeleteEventAdditionalBookingInformationOneYearJob.java
src/test/resources/test-postgres-rutherford-data-dump.sql

https://github.com/isaaccomputerscience/isaac-cs-issues/issues/315

renamed medical requirements to dietary requirements

---

compose-local-deps.yml
src/main/resources/db_scripts/postgres-rutherford-create-script.sql
src/test/java/uk/ac/cam/cl/dtg/isaac/api/IsaacIntegrationTest.java

https://github.com/isaaccomputerscience/isaac-cs-issues/issues/333

modified logged_events table settings, updated postgres version to 14

---

src/main/java/uk/ac/cam/cl/dtg/segue/api/AdminFacade.java
src/main/java/uk/ac/cam/cl/dtg/segue/etl/ETLFacade.java
src/test/java/uk/ac/cam/cl/dtg/segue/api/AdminFacadeTest.java

https://github.com/isaaccomputerscience/isaac-cs-issues/issues/355

removed endpoint for setting content version

---

web-api-live.xml
web-api-local.xml

[Ticket](https://github.com/isaaccomputerscience/isaac-cs-issues/issues/324)

[324]: Explicitly set cookie config as secure in web-api-live and -local

---

src/main/java/uk/ac/cam/cl/dtg/segue/api/SessionValidator.java

[Ticket](https://github.com/isaaccomputerscience/isaac-cs-issues/issues/323)
Improve error handling for malformed cookies in validation filter, to fix specific issue reported in ticket.

[323]: Improve error handling on auth-refresh response filter

---

pom.xml

This reverts commit 15e0df046d023657cb5c5240483e75960bd4af73.

Revert "Bump org.slf4j:slf4j-api from 1.7.36 to 2.0.12 (#145)"

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/Constants.java
src/main/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacade.java
src/main/java/uk/ac/cam/cl/dtg/isaac/api/managers/EventBookingManager.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dao/EventBookingPersistenceManager.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dos/eventbookings/PgEventBookings.java
src/test/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacadeIT.java
src/test/java/uk/ac/cam/cl/dtg/isaac/api/managers/EventBookingManagerTest.java
src/test/resources/test-postgres-rutherford-data-dump.sql

This reverts commit 464ef591bfd053d08a43db3acd77aa93065d2f2f.

Revert "Robert/317 cancellation auto enroll (#156)"

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacade.java

https://github.com/isaaccomputerscience/isaac-cs-issues/issues/373

removed teaching experience

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/managers/GameManager.java
src/test/java/uk/ac/cam/cl/dtg/isaac/api/managers/GameManagerTest.java

https://github.com/isaaccomputerscience/isaac-cs-issues/issues/378

added filter to exclude regression test from question finder, plus test

---

src/main/java/uk/ac/cam/cl/dtg/segue/search/ElasticSearchProvider.java

https://github.com/isaaccomputerscience/isaac-cs-issues/issues/396

changing date filter to seconds to fix display of events

---

src/main/java/uk/ac/cam/cl/dtg/isaac/quiz/PgQuestionAttempts.java
src/main/java/uk/ac/cam/cl/dtg/segue/api/managers/UserAuthenticationManager.java
src/main/java/uk/ac/cam/cl/dtg/segue/dao/PgLogManager.java

[Ticket](https://github.com/isaaccomputerscience/isaac-cs-issues/issues/397)

[397]: Fix date parsing error in getQuestionAttemptCountForUserByDateRange

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacade.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dos/IsaacEventPage.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dto/IsaacEventPageDTO.java
src/test/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacadeTest.java

https://github.com/isaaccomputerscience/isaac-cs-issues/issues/387

allow users to join booked events from the platform

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacade.java

https://github.com/isaaccomputerscience/isaac-cs-issues/issues/408

removed sorting of event overviews

---

src/main/java/uk/ac/cam/cl/dtg/isaac/dos/IsaacEventPage.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dto/IsaacEventPageDTO.java

Following from this ticket in the Content Editor - https://github.com/isaaccomputerscience/isaac-cs-issues/issues/416

added the publicationDate types in the DO and DTO in the API

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacade.java

[Ticket](https://github.com/isaaccomputerscience/isaac-cs-issues/issues/425)

[425]: Add reservation count to values provided by events summary endpoint

---

src/main/java/uk/ac/cam/cl/dtg/util/Mailer.java

[Ticket](https://github.com/isaaccomputerscience/isaac-cs-issues/issues/85)

[85]: Set checkserveridentity to true in mailer properties

---

Dockerfile
Dockerfile-api
Dockerfile-etl
pom.xml
src/main/java/uk/ac/cam/cl/dtg/isaac/configuration/exceptionmappers/OptionsMethodExceptionMapper.java
src/main/java/uk/ac/cam/cl/dtg/segue/api/managers/UserAuthenticationManager.java
src/main/java/uk/ac/cam/cl/dtg/segue/api/useralerts/UserAlertsWebSocket.java
src/main/java/uk/ac/cam/cl/dtg/segue/api/useralerts/UserAlertsWebSocketServlet.java
src/test/java/uk/ac/cam/cl/dtg/isaac/api/AuthenticationFacadeIT.java
web-api-live.xml
web-api-local.xml
web-etl.xml

This reverts commit bdaa26bb2667874327e667fdb51f9c5a2d4aa797.
Branch worked locally but failed to start on staging. Reverting commit until a fix is implemented.

Revert "Robert/279 jetty 12 migration (#207)"

---

Dockerfile
Dockerfile-api
Dockerfile-etl
pom.xml
resources/jetty.xml
src/main/java/uk/ac/cam/cl/dtg/isaac/configuration/exceptionmappers/OptionsMethodExceptionMapper.java
src/main/java/uk/ac/cam/cl/dtg/segue/api/managers/UserAuthenticationManager.java
src/main/java/uk/ac/cam/cl/dtg/segue/api/useralerts/UserAlertsWebSocket.java
src/main/java/uk/ac/cam/cl/dtg/segue/api/useralerts/UserAlertsWebSocketServlet.java
src/test/java/uk/ac/cam/cl/dtg/isaac/api/AuthenticationFacadeIT.java
web-api-live.xml
web-api-local.xml
web-etl.xml

This reverts commit 2a47c55ff3417954585648efd464a203cdfcf39f.

Revert "Robert/279 jetty 12 migration (#247)"

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacade.java
src/test/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacadeIT.java
src/test/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacadeTest.java

Ticket: https://github.com/isaaccomputerscience/isaac-cs-issues/issues/171

shav/171 - Duplicate field in EventsFacade 

---

src/main/java/uk/ac/cam/cl/dtg/segue/api/ContactFacade.java

https://github.com/isaaccomputerscience/isaac-cs-issues/issues/224

Remove <br> tags in messages

---

src/main/resources/log4j2.yaml
src/test/resources/log4j2-test.yaml

Ticket: https://github.com/isaaccomputerscience/isaac-cs-issues/issues/329

shav/329: Log Injection Prevention

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/managers/EventNotificationEmailManager.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dos/IsaacEventPage.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dto/IsaacEventPageDTO.java

Ticket: https://github.com/isaaccomputerscience/isaac-cs-issues/issues/469

shav/469: Enhance feedback email system to include event surveys

---

src/main/java/uk/ac/cam/cl/dtg/isaac/dos/IsaacEventPage.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dto/IsaacEventPageDTO.java

In relation to this ticket: https://github.com/isaaccomputerscience/isaac-cs-issues/issues/469

changed the types the string for eventSurvey

---

src/main/java/uk/ac/cam/cl/dtg/isaac/dto/QuizAssignmentDTO.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dto/QuizAttemptDTO.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dto/UserGroupDTO.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dto/users/GroupMembershipDTO.java

https://github.com/isaaccomputerscience/isaac-cs-issues/issues/502

Test Bug - 502

---

src/main/java/uk/ac/cam/cl/dtg/isaac/api/EventsFacade.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dto/IsaacEventPageDTO.java
src/main/java/uk/ac/cam/cl/dtg/isaac/dto/eventbookings/CompetitionEntryDTO.java

Inelegant (but working) endpoint to allow writing competition entries as events

Competition Endpoint
